"""状态机模式常量。"""

MODE_BOOT = 'BOOT'
MODE_ALIGN = 'ALIGN'
MODE_DIRECTION = 'DIRECTION'
MODE_TURN = 'TURN'
MODE_ARC_FOLLOW = 'ARC_FOLLOW'
MODE_POLYLINE = 'POLYLINE'
MODE_PARK = 'PARK'
MODE_ARC_DONE = 'ARC_DONE'
MODE_FAULT = 'FAULT'
MODE_ESTOP = 'ESTOP'
